# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
            - name: releases-x
  # You may pin to the exact commit or the version.
  # uses: milankomaj/releases-x@9f5ea03219d88a877b5ad0c4f146474472f4a6ed
  uses: milankomaj/releases-x@v0.1
  with:
    # Use GITHUB_TOKEN
    GITHUB_TOKEN: # default is 
    # Use target branch
    target: # optional, default is master
    # Use title
    title: # optional, default is ${{ github.repository }}
    # Use tag
    tag: # optional, default is v.0.${{ github.run_id }}.${{runner.os}}
    # Use files
    files: # optional, default is 
    # Use rewrite
    rewrite: # optional
          
